# imap-cleaner log rotation
# Install to /usr/local/etc/newsyslog.conf.d/imap-cleaner.conf
#
# logfilename          owner:group  mode count size(KB) when  flags
/var/log/imap-cleaner.log imap-cleaner:imap-cleaner 640 7 1000 * Z
